### ISSUE TITLE
Links to www.sei.cmu.edu broken

### ISSUE THREAD

**Issue by couda** [BasLeijdekkers/MetricsReloaded#25]
The links in the "Lean more about ..." link to broken links from www.sei.cmu.edu.

For example: http://www.sei.cmu.edu/str/descriptions/cyclomatic_body.html

**Comment by Vincentv92** [comment]
Ran into the same problem. Used the Wayback machine and created a pdf version of the site.
Direct link: http://web.archive.org/web/20061229202606/http://www.sei.cmu.edu/str/descriptions/cyclomatic_body.html

**Comment by macagua** [comment]
@Vincentv92 thanks you :+1:
