### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by kay999** [BasLeijdekkers/MetricsReloaded#28]
Tried it on my projects, doesn't seem to find any files, regardles what scope/file/etc I choose in the inital dialog. Always shows everything as 0.

May have to do with the project structure, so I created a new "express"-project (NodeJS) from scratch, tried LOC metric on whole project or single file: Still only shows zeros. But it also doesn't work with my java-projects.

Plugin is 1.3.1, Idea is EAP 144.3891.8

**Comment by BasLeijdekkers** [comment]
Do you use the latest version of the plugin (1.3.1)?

**Comment by kay999** [comment]
Yes, Plugin is 1.3.1, Idea is EAP 144.3891.8.

**Comment by BasLeijdekkers** [comment]
There are several LOC metrics, which one(s) from which category did you try exactly? (categories: Project metrics, Module metrics, Package metrics, Interface metrics, Class metrics, Method metrics)

**Comment by kay999** [comment]
Doesn't matter what I try, the plugin seems not to find any files. It only shows "project" and everything is 0. Even for number of file metrics for example.

**Comment by BasLeijdekkers** [comment]
Strange. Could you maybe attach a test project so I can reproduce?

**Comment by kay999** [comment]
This is more or less an auto-created project:

[test1.zip](https://github.com/BasLeijdekkers/MetricsReloaded/files/138171/test1.zip)

**Comment by kay999** [comment]
And here the output: 
![metrics](https://cloud.githubusercontent.com/assets/14128442/13179316/af330f9a-d723-11e5-9639-45dd4a71e644.png)

**Comment by BasLeijdekkers** [comment]
The plugin handled your project setup incorrectly. It always expected a directory marked as source. This is now fixed. I will release the new version next Sunday.

**Comment by kay999** [comment]
Thank you.
