### ISSUE TITLE
PyCharm category

### ISSUE THREAD

**Issue by nicklasb** [BasLeijdekkers/MetricsReloaded#30]
Hi, 
I am running PyCharm, and it seem like this plugin doesn't work for me, or at least it doesn't appear. 
However it still seems like it is categorized as a PyCharm plugin, if there is no such intention, please remove it as such.

**Comment by BasLeijdekkers** [comment]
Hi Niklas,

The plugin should work, at least it did when I tested it on PyCharm Community Edition 5.0.4. At the bottom of the `Code` menu should be a `Calculate Metrics...` menu item. If you don't have it, there might be some error in the PyCharm log.

**Comment by nicklasb** [comment]
Thanks for you response.
Ok, it seems I misunderstood, then, I thought that was a built-in one as there were fewer alternatives than in the UI shown in the blog post.

![screen shot 2016-03-20 at 09 26 32](https://cloud.githubusercontent.com/assets/8634663/13903491/e7cb7290-ee7d-11e5-8d43-d5119601937a.png)

**Comment by BasLeijdekkers** [comment]
Yes, currently most metrics are Java only. Only the Lines of Code and Number of Files metrics are available for all languages. If you need any particular metric for Python or anything else, please let me know.

**Comment by nicklasb** [comment]
Basically all of them "would be nice".  :-)
For my own usage, dependency stuff would perhaps be the most interesting.
I'll get back if an explicit need should arise.
