### ISSUE TITLE
Support for Kotlin files

### ISSUE THREAD

**Issue by Hendrik-AS** [BasLeijdekkers/MetricsReloaded#33]
It would be nice if the plugin also supported kotlin files at least for line counting

**Comment by BasLeijdekkers** [comment]
MetricsReloaded supports Kotlin since version 1.2. For this to work the Kotlin plugin has to be installed (naturally:-). Does it not work for you?

**Comment by Hendrik-AS** [comment]
unfortunately it does not. I have plugin version 1.7 installed and it seems like it only counts the loc from the very few java files in my project. I have a gradle based android project. My kotlin files are under src/main/java. Can this be a problem?

**Comment by BasLeijdekkers** [comment]
Maybe MetricsReloaded doesn't understand something about your project setup. Is your project open source by any chance? Or can you share your project files (specifically the *.iml files)?

**Comment by Hendrik-AS** [comment]
unfortunately it is not open source but I think iml files should not hurt [imls.zip](https://github.com/BasLeijdekkers/MetricsReloaded/files/356910/imls.zip)

**Comment by BasLeijdekkers** [comment]
And which metrics are you trying to use? The built-in "Lines of code metrics" profile perhaps?

**Comment by Hendrik-AS** [comment]
"Whole Project", "Include test sources", "Lines of code metrics",

**Comment by Hendrik-AS** [comment]
I just checked everything again - maybe I am just stupid. Until now I only checked the package metrics where I end up with about 300 LOC with only a fraction of my packages displayed. The other metrics however seem to be fine. I did not check this before since I was discouraged by the results from the package metrics page

**Comment by BasLeijdekkers** [comment]
Ah yes, the package metrics were indeed not working for languages other than Java. This is now [fixed] (https://github.com/BasLeijdekkers/MetricsReloaded/commit/053d8ea687da95f0bb4b3db276a2c533bd2c469e) and I will release an updated version of MetricsReloaded soon. Thanks for your help and let me know if you have any other problems.

**Comment by Hendrik-AS** [comment]
sorry for not checking the whole story before complaining. Thanks for the help!
