### ISSUE TITLE
Metrics profiles not saves on restart of IntelliJ

### ISSUE THREAD

**Issue by BartCr** [BasLeijdekkers/MetricsReloaded#34]
Profiles for metrics are not saved for later re-use. This is because of 

java.io.FileNotFoundException: <userdir>.IntelliJIdea2016.2\config\metrics\SIG Unit Interfacing.xml (The system cannot find the path specified)

Creating the metrics directory in the IntelliJ configuration directory resolves the exception.

**Comment by denysobukh** [comment]
Observing the same bug:

1 install plug-in Metrics Reloaded v1.8
2 go to Analyse - Calculate metrics - browse Metrics profile in Metrics profile section
3 Add new profile, click Apply
4 restart IDE
5 there is no added profile in Metrics profile list

IU-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1440x900, 1920x1080; Retina

Is it going to be fixed?
