### ISSUE TITLE
Add "How to Build" Documentation

### ISSUE THREAD

**Issue by wje600** [BasLeijdekkers/MetricsReloaded#39]
It would make it easier to use/contribute to the project if there were some documentation on how to get it to build.

**Comment by BasLeijdekkers** [comment]
Somebody already made a good start with this, but unfortunately it's in Russian: https://github.com/shurik111333/MetricsReloaded/commit/5e1720358b1ec1929fff26e43d0c78cf5d19f78d#diff-3a9efde467c227a3e569aed0ccb180d9

Here's the Google translated version:

How to build the plugin:
0) Open the project
1) Add the IDEA Plugin SDK
    File -> Project structure
    In the left pane, under Project Settings, click Project
    In the right pane, under Project SDK, click New -> Intellij Platform Plugin SDK
    In the window that appears, specify the folder with Intellij IDEA installed
2) Add plug-in libraries to the SDK
    File -> Project structure
    In the left pane under Platform Settings, select SDKs
    From the list on the right select the one created in the first step of the SDK
    Add jar files to the "Classpath" list from the following folders:
* Idea_directory * \ plugins \ Kotlin \ lib
* Idea_directory * \ plugins \ Kotlin \ kotlinc
* Idea_directory * \ plugins \ Groovy \ lib

3) Launch Project Build

**Comment by wje600** [comment]
Perhaps there are some missing details (versions, etc.) that, if supplied, would make these instructions work. As shown above, I am unable to succeed.

**Comment by BasLeijdekkers** [comment]
Which error do you get exactly?

**Comment by wje600** [comment]
After considerable exploration, I believe I have discovered the essence of the difficulty: The project in general appears to be oriented around the Ultimate Edition of IntelliJ, which contains built-in support for various file types - such as JavaScript, CSS, etc. Attempting to build using the Community Edition of IntelliJ leads to quite a number of missing libraries and dependencies. (As an aside, I discovered that I was able to resolve these dependencies by downloading WebStorm, the web-oriented IDE from JetBrains, and adding various libraries.)

**Comment by BasLeijdekkers** [comment]
That is valuable information. Thank you for the feed back, I will incorporate this in the documentation.

**Comment by BasLeijdekkers** [comment]
instructions are added to the README.md
